services:
    mysql:
        image: mysql:9.1.0
        restart: always
        environment:
            MYSQL_DATABASE: symfony_todo_app
            MYSQL_ROOT_PASSWORD: password
        ports:
            -   "3306:3306"
        volumes:
            -   docker-example-symfony-mysql:/var/lib/mysql

volumes:
    docker-example-symfony-mysql: